apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Project-MarKRITIS/platform
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true